import { db } from '@/firebase/config'; // Your standard Firebase config
import { doc, getDoc } from 'firebase/firestore';

/**
 * @SABI_AUTH_LOCKED
 * DO NOT EDIT THIS FILE.
 * Replacing this logic will break the share page.
 */

export async function getTopicById(id: string) {
  // Use a log to see what is happening in the terminal
  console.log(`[Sabi Fetch] Attempting to fetch story ID: "${id}"`);

  if (!db) {
    console.error("[Sabi Fetch] Error: Firestore 'db' is not initialized!");
    return null;
  }

  try {
    const docRef = doc(db, 'weeklyEducationalTopics', id);
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      console.log(`[Sabi Fetch] Success: Found story "${docSnap.data().title}"`);
      return { id: docSnap.id, ...docSnap.data() };
    } else {
      console.log(`[Sabi Fetch] Fail: No document found with ID "${id}"`);
      return null;
    }
  } catch (error) {
    console.error("[Sabi Fetch] Exception:", error);
    return null;
  }

}