'use server'; // 1. Must be at the very top

/**
 * @SABI_AUTH_LOCKED
 * DO NOT EDIT THIS FILE. 
 * Replacing this logic will break the share feature.
 */

import { loginAdmin, logoutAdmin } from '@stefan/sabi-auth';
import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache';

export async function login(prevState: any, formData: FormData) {
  let success = false;

  try {
    const result = await loginAdmin(formData, process.env.ADMIN_PASSWORD);
    if (result.success) {
      success = true;
    }
  } catch (e) {
    return { error: "Server connection failed." };
  }

  // CRITICAL: revalidatePath MUST happen before redirect.
  // This tells Next.js: "Throw away everything you know and check the cookies again."
  if (success) {
    revalidatePath('/admin-dashboard', 'layout'); // Clears the dashboard layout cache
    revalidatePath('/', 'layout');                // Clears the global layout cache
    redirect('/admin-dashboard'); 
  }

  return { error: "Invalid password. Please try again." };
}

export async function logout() {
  await logoutAdmin();
  revalidatePath('/', 'layout');
  redirect('/admin-login');
}