'use server'; // 1. Must be at the very top

/**
 * @SABI_AUTH_LOCKED
 * DO NOT EDIT THIS FILE. 
 * Replacing this logic will break the share feature.
 */

import { loginAdmin, logoutAdmin } from '@stefan/sabi-auth';
import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache';

export async function login(prevState: any, formData: FormData) {
  // --- LOGGING ---
  // This will ONLY appear in your Terminal (where you run npm run dev)
  // It will NOT appear in the Chrome/Browser console.
  console.log("Sabi: Login Action Triggered");

  let isSuccess = false;

  try {
    const result = await loginAdmin(formData, process.env.ADMIN_PASSWORD);
    console.log("Sabi: Library result:", result);

    if (result.success) {
      isSuccess = true;
    } else {
      return { error: "Invalid credentials." };
    }
  } catch (error) {
    console.error("Sabi: Error during login logic:", error);
    return { error: "A server error occurred." };
  }

  // 2. CRITICAL: Redirect MUST happen outside the try/catch block
  // in some Next.js versions, otherwise the redirect is "caught" as an error.
  if (isSuccess) {
    revalidatePath('/', 'layout');
    redirect('/admin-dashboard');
  }
}

export async function logout() {
  await logoutAdmin();
  revalidatePath('/', 'layout');
  redirect('/admin-login');
}